# Generated by Django 5.0.1 on 2024-02-06 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.CASCADE, to='thirdapp.client', to_field='name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderdate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, to='thirdapp.product', to_field='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='appenddate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
