# Generated by Django 5.0.1 on 2024-02-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdapp', '0005_remove_productadmin_category_delete_categoryadmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='thirdapp/'),
        ),
    ]
