# Generated by Django 5.0.1 on 2024-02-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdapp', '0007_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='iphone-card-40-iphone15prohero-202309_FMT_WHH', null=True, upload_to='thirdapp/'),
        ),
    ]
