# Generated by Django 5.0.1 on 2024-02-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0002_productadmin_date_added_productadmin_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryAdmin',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='ProductAdmin',
            new_name='Product',
        ),
    ]
