# Generated by Django 5.0.1 on 2024-02-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Side',
        ),
    ]
